version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env_compose
    ports:
      - "8080:8000"


  database:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app

